### ISSUE TITLE
Wifi Error CCMP replay detected

### ISSUE THREAD

**Issue by JosemyAB** [john30/ebusd-esp32#54]
I'm using the v5 adapter with this setup:
<img width="1016" alt="image" src="https://github.com/john30/ebusd-esp32/assets/13203575/1179fcce-5e25-4c4c-8269-e9e32451493c">

**Ebus mode is plain**

I'm runing the ebusd deamon in a docker container with this setup:
```
# EBUSD
  ebusd: 
    container_name: ebusd 
    image: john30/ebusd:v23.3
    privileged: true
    environment: 
      EBUSD_DEVICE: "192.168.1.170:9999" 
      EBUSD_ACCESSLEVEL: "*" 
      EBUSD_SCANCONFIG:
      EBUSD_CONFIGPATH: "/ebusd-configuration/latest/en" 
      EBUSD_POLLINTERVAL: 10
      EBUSD_LATENCY: 20
      EBUSD_MQTTINT: "/ebusd-configuration/mqtt-hassio.cfg"
      EBUSD_MQTTJSON: ""
      EBUSD_MQTTHOST: "192.168.1.6" 
      EBUSD_MQTTPORT: "1883"
      EBUSD_MQTTUSER: "****"
      EBUSD_MQTTPASS: "****"
      TZ: "Europe/Madrid"      
    volumes: 
      - /docker/ebusd/etc:/etc/ebusd 
      - /docker/ebusd/ebusd-configuration:/ebusd-configuration
      - /docker/ebusd/var:/var
      - /etc/localtime:/etc/localtime:ro 
    restart: always 
    depends_on: 
      - mosquitto
```

And I get a lot of warnings:
```
Warning	
host: errors: protocol
```

And this error:
```
wifi:
19:38:49		
CCMP replay detected: A1=dc:54:75:92:8c:9c A2=04:d9:f5:c5:f5:30 PN=21749, RSC=21750 seq=52960
```
<img width="982" alt="image" src="https://github.com/john30/ebusd-esp32/assets/13203575/843c95a6-ff0d-4952-8340-3361270b579b">

I'm running the last version of the firwmare (2024-03-30) and ebusd 23.3

Am I doing something wrong?
